name: Deploy site
on:
  push:
    branches:
      - scratch/deploy-site
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch tags for more informative git-describe output.
          fetch-depth: 0
      - uses: metrumresearchgroup/actions/mpn-latest@v1
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true
          extra-repositories: 'https://mpn.metworx.com/snapshots/stable/${{ env.MPN_LATEST }}'
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown
      - name: Build site
        run: pkgdown::build_site_github_pages(dest_dir = "docs", install = TRUE)
        shell: Rscript {0}
      - uses: metrumresearchgroup/actions/subdir-to-gh-pages@v1
